<?php

/**
 * Seeded en translations of the bot's Arabic texts (design 2026-09-21 §2).
 *
 * Keys are the MASKED sources (App\Bot\Language\TranslationMask: numbers, links and
 * emoji replaced by ⟦n⟧), so one entry serves every order number and price.
 *
 * Generated by `php artisan bot:translations --warm --export`, then reviewed by hand.
 * A translation the owner edits in Settings → الترجمات becomes `human` in the database
 * and is never overwritten by this file.
 */
return [
    '- للاسف يا فندم غير متاح تفعيل كود خصم من خلالنا
- للاسف حاليا غير متاح اكواد خصم' => '- Sorry, we can\'t apply discount codes for you
- Unfortunately we don\'t have discount codes available right now',
    '⟦0⟧
تحبي تبدليها ولا تشيليها من الأوردر؟' => '⟦0⟧
Do you want to swap it or remove it from the order?',
    'تسوقي من الموقع' => 'Shop the website',
    'صورة' => 'image',
    'كان متوقع يوصل' => 'was supposed to arrive',
    'متوقع يوصل' => 'arriving',
    'محتاج عناوين الفروع ومواعيد العمل' => 'Need branch addresses and working hours',
    '⟦0⟧ موجودة في اختياراتك خلاص' => '⟦0⟧ is already in your selections',
    '⟦0⟧ يا فندم يومك حلو ان شاء الله ⟦1⟧ مع حضرتك ميار من Le Voile
إزاي أقدر أساعد حضرتك؟' => '⟦0⟧ Hi there, hope you\'re having a good day ⟦1⟧ I\'m Mayar from Le Voile
How can I help you?',
    '⟦4⟧. ⟦3⟧ × ⟦5⟧ — ⟦6⟧ ج.م
⟦7⟧. ⟦1⟧ × ⟦8⟧ — ⟦9⟧ ج.م
⟦10⟧. ⟦0⟧ × ⟦11⟧ — ⟦12⟧ ج.م
⟦13⟧. ⟦2⟧ × ⟦14⟧ — ⟦15⟧ ج.م

اختاري القطعة اللي عايزة ترجعيها ⟦16⟧' => '⟦4⟧. ⟦3⟧ × ⟦5⟧ — ⟦6⟧ EGP
⟦7⟧. ⟦1⟧ × ⟦8⟧ — ⟦9⟧ EGP
⟦10⟧. ⟦0⟧ × ⟦11⟧ — ⟦12⟧ EGP
⟦13⟧. ⟦2⟧ × ⟦14⟧ — ⟦15⟧ EGP

Choose which item you want to return ⟦16⟧',
    'Item name
details..
* Material :
* Dimension :
لتأكيد الأوردر عن طريق Website
Thanks for choosing Le Voile' => 'Item name
details..
* Material :
* Dimension :
To confirm your order via Website
Thanks for choosing Le Voile',
    'Thank you for contacting us. We\'re not planning to participate in any events at the moment, but we look forward to potential collaboration in the near future
شكرًا لتواصلكم معنا. في الوقت الحالي لا نشارك في أي فعاليات، لكن نتطلع بكل سرور إلى فرص تعاون مستقبلية قريبة' => 'Thank you for contacting us. We\'re not planning to participate in any events at the moment, but we look forward to potential collaboration in the near future
شكرًا لتواصلكم معنا. في الوقت الحالي لا نشارك في أي فعاليات، لكن نتطلع بكل سرور إلى فرص تعاون مستقبلية قريبة',
    'Thank you for reaching out and for your interest. At the moment, we don\'t require this service, but we\'ll keep your details in case we need it in the future. Appreciate it.
شكرًا لرسالتكم واهتمامكم. في الوقت الحالي إحنا مش محتاجين الخدمة، ولو احتجنا مستقبلاً هنرجع نتواصل معاكم. تقديرنا ليكم.' => 'Thank you for reaching out and for your interest. At the moment, we don\'t require this service, but we\'ll keep your details in case we need it in the future. Appreciate it.
شكرًا لرسالتكم واهتمامكم. في الوقت الحالي إحنا مش محتاجين الخدمة، ولو احتجنا مستقبلاً هنرجع نتواصل معاكم. تقديرنا ليكم.',
    'آسفين جدًا لده، الشكوى بخصوص إيه؟' => 'Really sorry about that, what\'s the complaint about?',
    'أبدلها' => 'Swap it',
    'أبدلها بدل كده' => 'Exchange it instead',
    'أبريل' => 'April',
    'أشيلها' => 'Remove it',
    'أغسطس' => 'August',
    'أقدر أساعد حضرتك إزاي؟ اختاري من القائمة' => 'How can I help you? Pick from the menu',
    'أقدر أساعدك في حاجة من دول:' => 'I can help you with one of these:',
    'أكتوبر' => 'October',
    'أكتوبر والشيخ زايد' => 'October & Sheikh',
    'أكيد، ممكن تقوليلي باختصار محتاجة إيه؟ عشان أوصّلك للشخص المناسب على طول' => 'Sure, can you tell me quickly what you need? So I can get you to the right person right away',
    'أنهي فرع بالظبط؟' => 'Which branch exactly?',
    'أهلاً
شكرًا لتواصلك معنا بخصوص الريفوند. أحب أطمنك أن جميع الريفوندات تتم وفقًا للإجراءات الرسمية للشركة، وعادةً ما تستغرق من ⟦0⟧ إلى ⟦1⟧ يوم عمل منذ إتمام العملية من قبلنا.
نحن ملتزمون بهذه الفترة لضمان أن جميع العمليات تتم بشكل آمن ومنظم، ولا يمكن تجاوز هذا الإطار الزمني.
في حال تجاوز المدة، يمكنك التواصل معنا مرة أخرى لمتابعة حالتك، وسنقوم بالتحقق مع فريق الحسابات لضمان استلامك للمستحقات في أسرع وقت ممكن.
شاكرين لك صبرك وتفهمك' => 'Hi
Thanks for reaching out about your refund. I want to reassure you that all refunds follow the company\'s official procedures and usually take ⟦0⟧ to ⟦1⟧ business days from when we process it.
We stick to this timeline to make sure everything goes through safely and smoothly, and we can\'t go beyond it.
If it takes longer, get back to us and we\'ll check with our accounting team to make sure you get what\'s due as soon as possible.
Thanks for your patience',
    'أهلاً بيكي ⟦0⟧
مساء الخير يا فندم يومك حلو ان شاء الله ⟦1⟧ مع حضرتك ميار من Le Voile
إزاي أقدر أساعد حضرتك؟' => 'Welcome ⟦0⟧
Good evening! Hope you\'re having a lovely day ⟦1⟧ I\'m Mayar from Le Voile
How can I help you?',
    'أهلاً بيكي' => 'Welcome',
    'أهلاً يا ⟦0⟧، أوردر #⟦1⟧ — تحبي تلغيه ولا تعدلي فيه؟' => 'Hi ⟦0⟧  order #⟦1⟧ — want to cancel it or make changes?',
    'أهلاً يا ⟦0⟧، أوردر #⟦1⟧ (اتطلب يوم ⟦2⟧ — ⟦3⟧)
الحالة: ⟦4⟧
متوقع يوصل: ⟦5⟧
تتبع الشحنة: ⟦6⟧' => 'Hi ⟦0⟧  order #⟦1⟧ (placed ⟦2⟧ — ⟦3⟧)
Status: ⟦4⟧
Expected delivery: ⟦5⟧
Track shipment: ⟦6⟧',
    'أهلاً يا ⟦0⟧، لقيت أوردر #⟦1⟧ — تحبي ترجعي ولا تبدلي؟' => 'Hi ⟦0⟧  found order #⟦1⟧ — want to return it or exchange?',
    'أيوه' => 'Yes',
    'أيوه تمام' => 'Yeah, that\'s fine',
    'إرجاع' => 'Return',
    'إلغاء' => 'Cancel',
    'إلغاء أو تعديل أوردر' => 'Cancel or edit order',
    'إيه سبب الاستبدال؟' => 'Why are you exchanging it?',
    'إيه سبب المرتجع؟' => 'Why are you returning it?',
    'ابدأ من جديد' => 'Start over',
    'ابعتيلي صورة للقطعة' => 'Send me a photo of the item',
    'ابعتيلي لينك المنتج اللي عايزاه بدلها، أو اكتبي المقاس/اللون الجديد' => 'Send me a link to the product you want instead, or just tell me the new size/color',
    'ابعتيلي لينك المنتج اللي عايزة تبدلي بيه من الموقع (من levoilestores.com)' => 'Send me the product link you want to exchange it with from the site (from levoilestores.com)',
    'اتأكد وجاري تجهيزه' => 'Confirmed and being prepared',
    'اتجهز ومستني شركة الشحن' => 'Ready and waiting for shipping company',
    'اتجهز وهيتسلم لشركة الشحن قريب' => 'Ready and will be picked up by shipping company soon',
    'اتسلم' => 'Delivered',
    'اتشحن' => 'Shipped',
    'اتشحن ومع شركة الشحن' => 'Shipped and with shipping company',
    'اتكلم' => 'speak',
    'اتلغى' => 'Cancelled',
    'اتواصل' => 'contact',
    'احكيلي حصل إيه بالتفصيل عشان نقدر نساعد حضرتك (ولو فيه صورة ابعتيها)' => 'Tell me exactly what happened so we can help (and send a photo if you have one)',
    'اختاري القطعة اللي عايزة تبدليها' => 'Choose the item you want to exchange',
    'اختاري القطعة اللي عايزة ترجعيها' => 'Choose the item you want to return',
    'اختاري القطعة اللي عايزة ترجعيها أو تبدليها' => 'Pick the item you want to return or exchange',
    'اختاري القطعة اللي عايزة تعدلي فيها' => 'Pick the item you want to change',
    'استبدال' => 'Exchange',
    'اسم' => 'Name',
    'اسمي' => 'My name',
    'اكتبي أرقام القطع اللي عايزاها، مثلًا: ⟦0⟧ و ⟦1⟧' => 'Type the item numbers you want, for example: ⟦0⟧ and ⟦1⟧',
    'اكتبي اسم الفرع، أو اختاري المنطقة من هنا' => 'Type the branch name or pick the area from here',
    'اكتبي اسم القطعة اللي عايزة ترجعيها أو تبدليها' => 'Tell me the name of the item you want to return or exchange',
    'اكتبي اسم القطعة اللي عايزة تعدلي فيها' => 'Tell me the name of the item you want to alter',
    'اكتبي العنوان الجديد بالتفصيل (المحافظة - المنطقة - الشارع)' => 'Write the new address in full (governorate - area - street)',
    'اكتبي رقم الموبايل الجديد' => 'Write the new phone number',
    'اكلم' => 'talk',
    'اكلمكم' => 'talk to you',
    'اكلمه' => 'talk to them',
    'الأحد' => 'Sunday',
    'الأربعاء' => 'Wednesday',
    'الأرقام دي مش مطابقة. جربي تاني، اكتبي آخر ⟦0⟧ أرقام من الموبايل اللي طلبتي بيه' => 'Those digits don\'t match, try again — text the last ⟦0⟧ digits of the phone number you ordered with',
    'الأوردر #⟦0⟧ ملغي أصلاً' => 'Order #⟦0⟧ is already canceled',
    'الأوردر اتأخر' => 'Order is late',
    'الأوردر ده عدّى على استلامه أكتر من ⟦0⟧ يوم، والمرتجع والاستبدال عندنا خلال ⟦1⟧ يوم من الاستلام بس.
لو تحبي، أحوّلك لحد من الفريق يساعدك.' => 'This order was received more than ⟦0⟧ days ago, and we only do returns and exchanges within ⟦1⟧ days of delivery.
If you\'d like, I can connect you with someone from our team to help.',
    'الأوردر لسه في معاده، متوقع يوصل من ⟦0⟧، ولو اتأخر عن كده ابعتيلي وهتابعه فورًا' => 'Your order is on schedule, expected between ⟦0⟧, if it\'s late let me know and I\'ll follow up right away',
    'الإثنين' => 'Monday',
    'الإسكندرية' => 'Alexandria',
    'الاسم' => 'Name',
    'الاوردر بيوصل القاهرة / الجيزة / الاسكندريه خلال ⟦0⟧ ايام عمل .
باقي المحافظات خلال ⟦1⟧ ايام عمل
غير محسوب الاجازات الرسميه والاسبوعيه' => 'Orders reach Cairo / Giza / Alexandria within ⟦0⟧ business days.
Other governorates within ⟦1⟧ business days
Not counting official and weekly holidays',
    'البونيهات
من ⟦0⟧ ج حتي ⟦1⟧ ج
لتأكيد الأوردر عن طريق ال Website
⟦2⟧
Thanks for choosing Le Voile' => 'Bonnets
From ⟦0⟧ EGP to ⟦1⟧ EGP
To confirm your order through the Website
⟦2⟧
Thanks for choosing Le Voile',
    'التجمع الخامس' => 'Fifth Settlement',
    'التعديل' => 'Change',
    'التعديل المطلوب' => 'What needs to be changed',
    'التفاصيل' => 'Details',
    'التليفون' => 'Phone',
    'الثلاثاء' => 'Tuesday',
    'الجمعة' => 'Friday',
    'الجيزة' => 'Giza',
    'الخصومات متاحه اونلاين و في كل فروعنا يا فندم و لكن احنا اونلاين فقط ادارة منفصله عن الفروع لو حضرتك بتسألي علي قطعه محددة ممكن تتواصلي مع الفرع بنفسك تتأكدي من توافرها قبل التوجه للفرع و تم توضيح لحضرتك كل عناوين الفروع و ارقامهم' => 'Discounts are available online and in all our branches. But we\'re a separate team for online orders from the physical branches. If you\'re asking about a specific item, you can contact the branch directly to confirm they have it before going there. We\'ve already shared all branch addresses and numbers with you',
    'الخميس' => 'Thursday',
    'الدعم' => 'support',
    'الدفع كاش عند الاستلام، أو فيزا / ماستركارد، أو Apple Pay، أو أي محفظة إلكترونية (من الموقع)' => 'Cash on delivery, or visa/mastercard, or Apple Pay, or any e-wallet (from the website)',
    'الرحاب' => 'Rehab',
    'الرقم' => 'Number',
    'الزقازيق' => 'Zagazig',
    'السبب' => 'Reason',
    'السبت' => 'Saturday',
    'السعر مناسب لجودة الخامة يا فندم و التفاصيل اللى بنهتم بيها عشان نضمن ان المنتج يكون بكواليتي عالية و مميز' => 'The price matches the fabric quality and the details we care about to make sure you get a high-quality, special product',
    'الشحن خارج مصر :
- الاوردر بيتم عن طريق الويب سايت
- تكلفه الشحن بيتم تحدديها حسب وزن الشحنة
- مدة التوصيل من ⟦0⟧ الي ⟦1⟧ ايام
وده لينك الويب سايت: ⟦2⟧
Thanks for choosing Le Voile
—
International Shipping (Outside Egypt): Orders can be placed through our website. Shipping cost is calculated based on the weight of the package. Delivery time is between ⟦3⟧ to ⟦4⟧ days. Here\'s the website link: ⟦5⟧ Thanks for choosing Le Voile' => 'Shipping outside Egypt:
- Orders placed through the website
- Shipping cost depends on package weight
- Delivery takes ⟦0⟧ to ⟦1⟧ days
Here\'s the website link ⟦2⟧
Thanks for choosing Le Voile
—
International Shipping (Outside Egypt): Orders can be placed through our website. Shipping cost is calculated based on the weight of the package. Delivery time is between ⟦3⟧ to ⟦4⟧ days. Here\'s the website link ⟦5⟧ Thanks for choosing Le Voile',
    'الشحن والتوصيل' => 'Shipping & delivery',
    'الشكوى' => 'Complaint',
    'الطلب' => 'Request',
    'العفو، لو احتجتي أي حاجة أنا موجودة' => 'You\'re welcome, let me know if you need anything',
    'العفو يا فندم تحت أمرك في أي وقت' => 'You\'re welcome, here for you anytime',
    'العفو يا قمر' => 'You\'re welcome',
    'العملاء' => 'customers',
    'العنوان' => 'Address',
    'العنوان الجديد' => 'New address',
    'الفرع' => 'Branch',
    'الفروع' => 'Branches',
    'الفروع والمواعيد' => 'Branches & hours',
    'الفريق' => 'the team',
    'القائمة الرئيسية' => 'Main Menu',
    'القاهرة' => 'Cairo',
    'القطع' => 'Items',
    'القطع اللي اخترتيها متاحة للاستبدال بس' => 'The items you picked are available for exchange only',
    'القطع في الأوردر' => 'Items in order',
    'اللون' => 'Color',
    'اللينك ده مش واضح، ابعتيه من صفحة المنتج على الموقع' => 'That link isn\'t clear — send it from the product page on the site',
    'المدير' => 'the manager',
    'المرتجع والاستبدال' => 'Returns & Exchanges',
    'المسؤول' => 'the responsible one',
    'المعادي' => 'Maadi',
    'المقاس' => 'Size',
    'المقاس مش مظبوط' => 'Size doesn\'t fit',
    'المقاسات' => 'Sizes',
    'المقاسات موضحه علي الويب سايت يا فندم بالطول و العرض فالافضل تراجعي المقاسات لانها ادق من الوزن اللي بيختلف من جسم للتاني' => 'Measurements are listed on the website by length and width, so it\'s better to check those since they\'re more accurate than weight which varies from person to person',
    'المقطم' => 'El Mokattam',
    'المنتج البديل' => 'Replacement item',
    'المنتج اللي بعتيه' => 'The product you sent',
    'المنتج مصنوع من        و طريقة الغسيل و العناية موضحه علي الويب سايت بالفعل
طريقة الغسيل بتكون يدوي بماء بارد و بمسحوق خفيف زي الجل و بدون فرك او عصر' => 'The product is made from        and care instructions are on the website
Wash by hand in cold water with gentle detergent like gel, no rubbing or wringing',
    'المندوب حاول يسلمه ومعرفش' => 'Delivery agent tried to deliver but couldn\'t reach',
    'المنصورة' => 'Mansoura',
    'المهندسين' => 'Mohandessin',
    'الموبايل' => 'Phone number',
    'الموبايل الجديد' => 'New phone number',
    'الموديل' => 'Style',
    'الموديلات والأسعار' => 'Styles & Prices',
    'الموظف' => 'employee',
    'الموظفين' => 'employees',
    'النهارده' => 'Today',
    'امبارح' => 'Yesterday',
    'انا' => 'I',
    'انا حابه اوضح لحضرتك ان في ضغط في الرسايل وبيتم الرد من الاقدم للاحدث فبالتالي الافضل يافندم ان يتم ارسال رساله او رسالتين في وقت واحد علي الاقل للرد علي حضرتك بشكل اسرع .. وفي حاله ارسال اكثر من رساله الشات بيطلع فوق والرد بيكون متاخر اكتر يافندم .. ويارب دايما عند حسن ظن حضرتك' => 'Just so you know, we get a lot of messages and we reply from oldest to newest. So it\'s better if you send one or two messages at once instead of sending lots of separate ones — that way we can help you faster. If you send too many messages, the chat gets pushed up and we take longer to reply. Thanks for understanding',
    'انسان' => 'person',
    'بايظ / فيه عيب' => 'Damaged / defective',
    'بس' => 'That\'s all',
    'بس كدا' => 'That\'s all',
    'بس كده' => 'That\'s all',
    'بشري' => 'human',
    'بيانات الأوردر' => 'Order details',
    'تاريخ الزيارة' => 'Visit date',
    'تحب نحولك لموظف يساعد حضرتك؟' => 'Would you like me to connect you with someone?',
    'تحبي تبدليها بدل ما ترجعيها؟' => 'Want to exchange it instead of returning it?',
    'تحبي تختاري قطعة تانية؟' => 'Want to pick another item?',
    'تحبي ترجعي ولا تبدلي؟' => 'Want to return or exchange?',
    'تحبي تضيفي قطعة تانية؟' => 'Want to add another item?',
    'تحبي تعرفي إيه؟' => 'What would you like to know?',
    'تحبي حاجة تانية؟' => 'Anything else I can help with?',
    'تحبي نسيب ⟦0⟧ ونتابع ⟦1⟧؟' => 'Want to leave ⟦0⟧ and do ⟦1⟧ instead?',
    'تعديل' => 'Edit',
    'تعديل القطع' => 'Edit items',
    'تقدري تستبدلي او تسترجعي من اقرب فرع لحضرتك بالفتورة خلال ⟦0⟧ يوم فقط
مع العلم ان غير متاح استبدال او استرجاع في :
"المنتجات القطنيه والإكسسوارات ومكملات الحجاب والاسدالات portable والبوركيني والكاش مايوه"
بالاضافة ان في حالة وجود خصم علي القطعه بيكون متاح استبدال فقط غير متاح استرجاعها' => 'You can exchange or return at the nearest branch with your receipt within ⟦0⟧ days only
Keep in mind that exchanges and returns aren\'t available for:
"Cotton products, accessories, headscarf complements, portable asdals, burkini, and cash swimwear"
Also, if an item is on discount, you can only exchange it — returns aren\'t available',
    'تقدري تطلبي مباشرة من الموقع يا فندم
⟦0⟧
ولو حابة نسجل الأوردر مع حضرتك قوليلي وهحولك لموظف' => 'You can order directly from the website
⟦0⟧
Or if you\'d like us to register your order together, just say the word and I\'ll transfer you to an agent',
    'تليفون' => 'Phone',
    'تليفوني' => 'My phone',
    'تم التواصل مع شركه الشحن لمتابعه الاوردر و هيتم التواصل مع حضرتك من خلالهم في اقرب وقت للتسليم' => 'We\'ve reached out to the shipping company to track your order and they\'ll contact you soon to arrange delivery',
    'تم تسجيل شكوى حضرتك برقم #⟦0⟧ وهيتم التواصل مع حضرتك في أقرب وقت' => 'Your complaint has been recorded under #⟦0⟧ and we\'ll be in touch soon',
    'تم تسجيل طلب حضرتك برقم #⟦0⟧ وهيتم التواصل مع حضرتك في أقرب وقت
حابة أوضح إن الإلغاء أو التعديل متاح خلال ساعتين بس من وقت الطلب.' => 'Your request has been recorded under #⟦0⟧ and we\'ll be in touch soon
Just to be clear, you can cancel or edit within 2 hours of placing your order.',
    'تم تسجيل طلب حضرتك برقم #⟦0⟧ وهيتم التواصل مع حضرتك في أقرب وقت' => 'Your request has been registered under #⟦0⟧ and we\'ll be in touch soon',
    'تم عمل الريفوند لحضرتك بمجرد تحويل المبلغ نبعت لحضرتك سكرين شوت بالتحويل و بيسمع في حسابك في خلال من ⟦0⟧ ل ⟦1⟧ يوم عمل' => 'Your refund was processed. Once the amount is transferred we\'ll send you a screenshot and you should see it in your account within ⟦0⟧ to ⟦1⟧ business days',
    'تم عمل ريفوند لحضرتك بعد رجوع القطعه لينا من شركه الشحن بيتم تحويل المبلغ لحضرتك من قبل قسم الحسابات و بنبعت لك سكرين شوت بالتحويل و بتسمع في حسابك خلال من ⟦0⟧ ل ⟦1⟧ يوم عمل' => 'Your refund was processed once the item came back to us from the shipping company. The accounting team will transfer the amount to you and send you a screenshot of the transfer. You should see it in your account within ⟦0⟧ to ⟦1⟧ business days',
    'تمام' => 'Got it',
    'تمام، تم تسجيل طلب الاستبدال بـ ⟦0⟧. هنتواصل معاكي لتأكيد الاستبدال والإرسال' => 'Perfect, your exchange request is registered as ⟦0⟧. We\'ll contact you to confirm the exchange and send it out',
    'تمام، تم تقديم طلب المرتجع بنجاح، ورقم طلبك هو نفس رقم الأوردر #⟦0⟧. هنتواصل معاكي أول ما المندوب يتحرك لاستلام المرتجع' => 'Perfect, your return request is submitted, and your request number is the same as your order #⟦0⟧. We\'ll let you know as soon as the courier picks it up',
    'تمام، سجلت الشكوى رقم #⟦0⟧، والفريق هيتواصل معاكي في أقرب وقت' => 'Got it, complaint #⟦0⟧ registered, the team will be in touch soon',
    'تمام، سجلت طلب إلغاء أوردر #⟦0⟧، والفريق هيأكد معاكي الإلغاء في أقرب وقت' => 'Got it. I\'ve submitted a cancellation request for order #⟦0⟧, the team will confirm with you soon',
    'تمام، سجلت طلب تعديل أوردر #⟦0⟧، والفريق هيأكد معاكي التعديل' => 'Got it. I\'ve submitted an edit request for order #⟦0⟧, the team will confirm with you',
    'تمام، سجلت طلبك، وهيتم تحويلك لموظف خدمة العملاء أول ما نفتح ⟦0⟧' => 'Done. I\'ve logged your request and you\'ll be transferred to customer service as soon as we open ⟦0⟧',
    'تمام، لو احتجتي أي حاجة تانية أنا موجودة' => 'Perfect, let me know if you need anything else',
    'تمام، هنكمل الطلب استبدال' => 'Got it, let\'s continue with the exchange',
    'تمام، هيتم تحويلك لموظف خدمة العملاء خلال دقايق' => 'Done, you\'ll be transferred to customer service in a few minutes',
    'تمام، هيتم تحويلك لموظف خدمة العملاء، هيرد عليكي في أقرب وقت' => 'Done, you\'ll be transferred to customer service, they\'ll get back to you soon',
    'تمام، وممكن اسم حضرتك؟' => 'Got it — what\'s your name?',
    'تمام ⟦1⟧ ضفت: ⟦0⟧ × ⟦2⟧
تحبي تضيفي قطعة تانية؟' => 'All set, ⟦1⟧ added: ⟦0⟧ × ⟦2⟧
Want to add something else?',
    'تمام شكرًا' => 'Thanks, got it',
    'تمام كده' => 'That\'s it',
    'تمام وصلتني الصورة' => 'Got the photo',
    'تمام يا فندم، استني ثواني هحولك لموظف يسجل الأوردر مع حضرتك' => 'Sure, one moment while I connect you with an agent to place your order',
    'تمام يا فندم، هراجع طلب حضرتك مع الفريق حالًا وهرد عليكي' => 'Got it, I\'ll check your order with the team right now and get back to you',
    'جماعه' => 'everyone',
    'جميع الالوان الموجودة علي الويب سايت حاليا .. في حاله عدم تواجد اللون بيكون خلص والالوان المتاحه هي المتوفرة فقط' => 'All the colors on the website right now are what we have in stock. If a color isn\'t there, it\'s sold out — the colors showing are the only ones available',
    'حابة أوضح لحضرتك إن الاستبدال أو الاسترجاع بيكون خلال ⟦0⟧ يوم من استلام الأوردر، والقطعة تكون بحالتها الأصلية
وفي منتجات مش متاحة للاستبدال أو الاسترجاع زي المنتجات القطنية والإكسسوارات ومكملات الحجاب والإسدالات الـ portable والبوركيني والكاش مايوه، والقطعة اللي عليها خصم متاح استبدالها بس.' => 'Just to let you know, exchanges or returns are within ⟦0⟧ days of receiving your order, and the item needs to be in its original condition
Some items can\'t be exchanged or returned like cotton products, accessories, hijab add-ons, portable shawls, burkinis, and cash swimwear — but discounted items can be exchanged.',
    'حاجة تانية' => 'Something else',
    'حد' => 'someone',
    'حضرتك' => 'you',
    'حضرتك في أنهي منطقة؟ اختاري أو اكتبي اسم المنطقة أو الفرع' => 'Which area are you in? Choose or type the area or branch name',
    'حولني' => 'Connect me',
    'حولني على طول' => 'Connect me now',
    'حوليني' => 'Connect me',
    'حوّليني على طول' => 'Connect me now',
    'حوليني على طول' => 'Connect me now',
    'خدمة العملاء' => 'Customer Service',
    'خدمه' => 'service',
    'خلاص' => 'Done',
    'دا' => 'This',
    'ده' => 'This',
    'ده لينك فيه جميع الموديلات المتاحه يا فندم
ممكن حضرتك تحددلنا الشكل إللي حضرتك محتاجه وابعتلك التفاصيل
⟦0⟧' => 'Here\'s a link with all available styles
Just let us know which one you need and we\'ll send you the details
⟦0⟧',
    'ديسمبر' => 'December',
    'رجع لينا (مرتجع)' => 'Returned to us',
    'رجع من شركة الشحن' => 'Returned from shipping company',
    'رقم' => 'number',
    'رقم الأوردر' => 'Order number',
    'رقم الموبايل' => 'Phone number',
    'رقم تاني' => 'Different number',
    'رقمي' => 'My number',
    'سبب الإلغاء' => 'Reason for cancellation',
    'سبتمبر' => 'September',
    'سجلت طلب متابعة للأوردر #⟦0⟧، الفريق هيتابع مع شركة الشحن ويرد عليكي في أقرب وقت' => 'Logged follow-up for order #⟦0⟧  the team will check with shipping and get back to you soon',
    'سمحت' => 'please',
    'سياسة الاستبدال او الاسترجاع:-
-غير متاح معاينة الأوردر قبل الاستلام أو تجزئته
- الاستبدال او الاسترجاع بيكون خلال ⟦0⟧ يوم من تاريخ استلام الاوردر
في حالة وجود مشكله في الاوردر بيتم التواصل معنا وعمل اوردر استرجاع لو الديفوه من عندنا بيتم الاستبدال بدون مصاريف شحن
اما لو المشكله في المقاس او الموديل مش مناسب حضرتك بتتحملي مصاريف الشحن او ترجعيها لأقرب فرع ليكي بالريسيت
شرط ان تكون القطعه في حالتها الاصليه الي وصلت بيها
مع العلم غير متاح استبدال او استرجاع بعض الموديلات مثل
"المنتجات القطنيه (البونيهات , التربون , الباديهات) والإكسسوارات ومكملات الحجاب والاسدالات ال portable والبوركيني والكاش مايوه"
بالاضافه ان لو القطعه عليها خصم بيكون متاح استبدالها فقط' => 'Exchange and return policy:-
- Can\'t inspect the order before receiving it or split it up
- Exchanges or returns within ⟦0⟧ days from when you receive the order
If there\'s a problem with your order, let us know. If it\'s a defect on our end, we\'ll exchange it with no shipping fees.
If it\'s the size or style not being right for you, you cover shipping or return it to the nearest branch with the receipt.
The item has to be in its original condition.
Note that exchanges or returns aren\'t available for certain items like:
"Cotton products (bonnets, turbans, base layers), accessories, headscarf complements, portable drapes, burkini, and cash swimwear"
Also, if an item is on discount, it can only be exchanged',
    'شحن وتوصيل' => 'Shipping & Delivery',
    'شكرا لاهتمامك و إبداء رأيك، أحنا بنسمع لكل عميل و هنوصل ملاحظتك' => 'Thanks for your interest and feedback. We listen to every customer and we\'ll pass your comment along',
    'شكوى' => 'Complaint',
    'صباح الفل والنور' => 'Good morning',
    'صباح النور' => 'Good morning',
    'صورة العيب (تم)' => 'Defect photo (done)',
    'صورة المنتج (تم)' => 'Product photo (done)',
    'طرق الدفع' => 'Payment methods',
    'طريقة الغسيل والعناية وتفاصيل الخامة موضحة على الويب سايت في صفحة كل منتج يا فندم
⟦0⟧' => 'Care and fabric details are on the website on each product page
⟦0⟧',
    'طلب الإلغاء أو التعديل' => 'Cancel or edit order',
    'طلب المرتجع' => 'Return request',
    'طلب حضرتك متسجل برقم #⟦0⟧ وهيتم التواصل مع حضرتك، تحب نحولك لموظف؟' => 'Your request is recorded under #⟦0⟧ and we\'ll get back to you. Would you like to speak to someone?',
    'عاوز' => 'I want',
    'عاوزه' => 'I want',
    'عايز' => 'I want',
    'عايزة أرجع أو أبدل' => 'Want to return or',
    'عايزة ألغي/أعدل' => 'Cancel or edit',
    'عايزة تعدلي إيه؟' => 'What would you like to change?',
    'عايزه' => 'I want',
    'عايزين' => 'need',
    'ممكن اسم حضرتك ورقم الموبايل اللي نتواصل عليه؟' => 'Could I have your name and the mobile number we can reach you on?',
    'عشان الفريق يقدر يتواصل مع حضرتك ⟦0⟧ ابعتيلي اسمك ورقم موبايلك في رسالة واحدة (مثلاً: سارة ⟦1⟧)' => 'So the team can reach you at ⟦0⟧, send me your name and phone number in one message (like: Sara ⟦1⟧)',
    'عشان نخلص طلب حضرتك صح، تحبي أوصلك لموظف يساعدك؟' => 'To process your order properly, can I connect you with someone who can help?',
    'على طول' => 'Right away',
    'عليا' => 'to me',
    'عليه' => 'On it',
    'غلط في الأوردر' => 'Wrong item',
    'فبراير' => 'February',
    'فرع' => 'Branch',
    'فرع في منطقة تانية' => 'Another area',
    'فريق' => 'team',
    'فضلك' => 'please',
    'فلو الإلغاء والتعديل الجديد: قبل الشحن بس، سبب الإلغاء، وتعديل القطع أو العنوان أو الموبايل' => 'For cancellations and changes: only before shipping, tell us why you\'re canceling, and what you want to change — the item, address, or phone number',
    'فلو الشكوى الجديد: اسم الفرع أو المنطقة، الأوردر للشحن والمنتج، بيانات التواصل، وصور مع التفاصيل' => 'For complaints: which branch or area, your order details and the product, your contact info, and pictures with details',
    'فلو الفروع الجديد: كروت الفروع بالخريطة والاتصال، وفرع في منطقة تانية' => 'For branches: branch cards on the map with phone numbers, or a branch in another area',
    'فلو المرتجع والاستبدال الجديد: ترجعي ولا تبدلي، صورة للمرتجع، ولينك المنتج للاستبدال' => 'For returns and exchanges: do you want to return or exchange, a picture of what you\'re returning, and the link to the item you want instead',
    'فلو متابعة الأوردر الجديد: كارت الحالة وميعاد التوصيل، ومتابعة التأخير بس لما العميلة تطلب' => 'For order tracking: your order status and delivery date, and we\'ll follow up on delays when you ask',
    'فندم' => 'Sure thing',
    'فيه عيب' => 'Defective',
    'فيه فروع تانية، اكتبي اسم الفرع' => 'We have other branches — tell me which one',
    'قطعة تانية' => 'Another item',
    'قطعة ناقصة' => 'Missing item',
    'كام قطعة؟' => 'How many items?',
    'كانت الزيارة إمتى تقريبًا؟' => 'When did you visit, roughly?',
    'كدا تمام' => 'That\'s it',
    'كده تمام' => 'That\'s it',
    'كذا قطعة' => 'Several items',
    'كل الموديلات متاحه في كل الفروع يافندم
- ممكن حضرتك تتواصلي معاهم للتاكيد من وجود المنتج او تشرفينا بنفسك وتشوفي كل الموديلات المتاحه
لكن مقدرش اضمن لحضرتك اللون او الكميه برجاء التواصل مع الفرع للتأكد
- بالاضافه ان وارد ان المنتج يكون غير متاح ف الفروع لانه راجع حسب الضغط علي كل فرع' => 'All styles are available at all branches
- You can contact them to confirm the product is in stock, or visit us in person to see everything we have
But I can\'t guarantee the color or quantity — please check with the branch
- Also, it\'s possible an item might not be in branches since it depends on how busy each location is',
    'كلم موظف' => 'Talk to an agent',
    'لأ' => 'No',
    'لأ كده تمام' => 'No, that\'s it',
    'لأ نكمل' => 'No, carry on',
    'لا' => 'No',
    'لا شكرا' => 'No thanks',
    'لا كدا تمام' => 'No, that\'s it',
    'لا كده تمام' => 'No, that\'s it',
    'لاء' => 'No',
    'لتاكيد الاوردر برجاء ارسال :
الاسم بالكامل
- العنوان تفصيلي "المحافظة - المنطقة"
- رقم الموبايل
- غير متاح فتح الاوردر في تواجد المندوب
- وفي حاله حدوث اي مشكله بيتم التواصل معنا وبيتم عمل استبدال او استرجاع من خلالنا او من الفرع مع وجود الفاتوره .
مع العلم ان غير متاح استبدال او استرجاع في :
"المنتجات القطنيه والإكسسوارات ومكملات الحجاب والاسدالات portable والبوركيني والكاش مايوه"
بالاضافة ان في حالة وجود خصم علي القطعه بيكون متاح استبدال فقط غير متاح استرجاعها' => 'To confirm your order please send:
Full name
- Detailed address "governorate - area"
- Mobile number
- Can\'t open the order while the delivery agent is there
- If any issue comes up we\'ll reach out and handle an exchange or refund through us or at the nearest branch with receipt.
Note that exchanges or refunds aren\'t available for:
"Cotton products, accessories, headscarf complements, portable drapes, burkini, and cash swimwear"
Also, if an item is on discount, it can only be exchanged, not refunded',
    'لسه فاكرين طلبك، تحبي نكمل من حيث ما وقفنا؟' => 'We remember your order — want to pick up where we left off?',
    'لقيت الأوردر. للتأكيد، اكتبي آخر ⟦0⟧ أرقام من الموبايل اللي طلبتي بيه' => 'Got your order, to confirm it — text the last ⟦0⟧ digits of the phone number you ordered with',
    'للأسف الأوردر #⟦0⟧ اتشحن خلاص فمينفعش نلغيه أو نعدل فيه' => 'Sorry, order #⟦0⟧ has already shipped so we can\'t cancel or edit it',
    'للأسف مش لاقية الأوردر، تحبي أحولك لحد من الفريق يتابعه معاكي؟' => 'Sorry, I can\'t find order — want me to connect you with someone from the team?',
    'للأسف يا فندم، المعاينة مش متاحة وقت الاستلام، بس حضرتك بتستلمي المنتج زي ما هو متصور بالظبط على الموقع. ولو بعد الاستلام فيه أي مشكلة في المنتج، حضرتك بتتواصلي مع خدمة العملاء، وإحنا بنساعد حضرتك في الاستبدال أو حل أي مشكلة إن شاء الله' => 'Unfortunately, inspection at delivery isn\'t available, but you\'ll receive the product exactly as pictured on our site. If there\'s any issue after you receive it, just contact customer service and we\'ll help with an exchange or solution',
    'للاسف حاليا المنتج غير متاح تابعينا دائما و بمجرد ما يتوفر بيكون متاح علي الويب سايت
تقدري تشوفي الموديلات المتاحة من هنا
⟦0⟧' => 'Unfortunately the product isn\'t available right now. Keep following us and as soon as it\'s back in stock it\'ll be on the website.
You can see available styles here
⟦0⟧',
    'للاسف معندناش علم تحديدا احنا هنا خدمه العملاء
دا الاكونت البرايفت ل مدام ساره تقدري تستفسري منها
⟦0⟧' => 'Sorry, we don\'t have that info — we\'re customer service. This is the private account for Madam Sarah, you can ask her directly
⟦0⟧',
    'لو' => 'if',
    'لو حابة أحولك لموظف في أي وقت قوليلي' => 'If you\'d like me to connect you with an agent anytime, just let me know',
    'مارس' => 'March',
    'مايو' => 'May',
    'متابعة أوردر' => 'Track Order',
    'متابعة الأوردر' => 'Track order',
    'متوقف مؤقتًا والفريق بيراجعه' => 'Temporarily on hold while team reviews',
    'متوقف ومحتاج مراجعة' => 'On hold and needs review',
    'مدير' => 'manager',
    'مدينة نصر' => 'Nasr City',
    'مدينتي' => 'Madinet El Zahra',
    'مسؤول' => 'responsible',
    'مساء الفل والنور' => 'Good evening',
    'مساء النور' => 'Good evening',
    'مش عاجبني' => 'Don\'t like it',
    'مش قادر أتأكد من الأوردر ده' => 'Can\'t verify this order',
    'مش لاقية أوردر بالبيانات دي، ممكن تتأكدي من الرقم؟' => 'I can\'t find an order with that info. Can you double-check the number?',
    'مش مهم' => 'Doesn\'t matter',
    'مش مهم خالص' => 'Doesn\'t matter at all',
    'مصاريف الشحن بتتحسب حسب المحافظة وبتظهر لحضرتك قبل تأكيد الأوردر على الويب سايت' => 'Shipping costs are calculated by governorate and shown before you confirm your order on the website',
    'مصر الجديدة' => 'Masr El Gedida',
    'مع' => 'with',
    'مع المندوب في الطريق' => 'On the way with delivery agent',
    'مع المندوب في الطريق ليكي' => 'On the way to you',
    'معاك' => 'With you',
    'معاكم' => 'with you',
    'معاكي' => 'With you',
    'معاه' => 'with them',
    'معلش مش واضحة ليا، اختاري من دول:' => 'Sorry, I didn\'t catch that, please pick one:',
    'معلش، لسه مش قادرة أفهم قصدك، تحبي أوصلك لموظف يساعدك؟' => 'Sorry, I\'m not quite getting what you mean. Would you like to speak to someone who can help?',
    'مفيش' => 'Nothing',
    'ممكن' => 'Can I',
    'ممكن تكتبيلي سبب الإلغاء؟' => 'Can you tell me why you want to cancel?',
    'ممكن حضرتك ترجعي للفرع نقسه توضحي لهم المشكله اللي مع حضرتك لان احنا اونلاين فقط ادارة منفصله عن الفروع ولو في اي خطا من ناحيتنا بعد المراجعه تأكدي ان هيتم حله' => 'You can go back to the branch and explain the issue to them — we\'re a separate online team from the physical branches. If there\'s any mistake on our end, once they check, we\'ll make sure it gets fixed',
    'ممكن رقم الأوردر أو رقم الموبايل اللي اتعمل بيه الأوردر؟' => 'Can I get your order number or the phone number you used for it?',
    'ممكن رقم الاوردر او رقم الموبايل او الميل اللي تم بيه الاوردر عشان اقدر اساعد حضرتك
او صورة الفاتورة
• صورة واضحة للمنتج
• صورة الكود الموجود على التيكت' => 'Can I get your order number, phone number, or the email you used for the order? That would help me assist you
Or send a photo of your receipt
• A clear photo of the product
• A photo of the code on the tag',
    'ممكن رقم الاوردر او رقم الموبايل او الميل اللي تم بيه الاوردر عشان اقدر اساعد حضرتك
او صورة الفاتورة
• صورة واضحة للمنتج
• صورة توضح الديفوه الموجود في المنتج
• صورة الكود الموجود على التيكت' => 'Can I get your order number, phone number, or the email the order was placed with so I can help you?
Or a photo of the receipt
• Clear photo of the product
• Photo showing the defect in the product
• Photo of the code on the tag',
    'ممكن رقم الاوردر او رقم الموبايل او الميل اللي تم بيه الاوردر عشان اقدر اساعد حضرتك
حابه اوضح لحضرتك ان الغاء الاوردر او تعديله بيكون في خلال ساعتين فقط من وقت طلب الأوردر' => 'Can I get your order number, phone number, or the email you used for the order? That way I can help you
Just so you know, you can only cancel or edit your order within 2 hours of placing it',
    'ممكن رقم الاوردر او رقم الموبايل او الميل اللي تم بيه الاوردر عشان اقدر اساعد حضرتك
حابه اوضح لحضرتك ان فيما بعد الغاء الاوردر بيكون في خلال ساعتين فقط من الطلب لان بيكون في تحمل لمصاريف الشحن' => 'Can I get your order number, phone number, or the email you used for the order? That way I can help you
Just so you know, you can only cancel within 2 hours of placing the order, and there will be shipping fees to cover',
    'ممكن رقم الاوردر او رقم الموبايل او الميل اللي تم بيه الاوردر عشان اقدر اساعد حضرتك' => 'Can I get your order number, phone number, or the email the order was placed with so I can help you?',
    'ممكن رقم الموبايل اللي نتواصل مع حضرتك عليه؟' => 'Can I get the mobile number to reach you on?',
    'من' => 'from',
    'من كام يوم' => 'A few days ago',
    'منتج' => 'Product',
    'موبايل' => 'Phone',
    'موبايلي' => 'My phone',
    'موضوع التحويل:' => 'Transfer topic:',
    'موظف' => 'staff member',
    'موظفه' => 'staff member',
    'نرجع لـ⟦0⟧ ⟦1⟧
آسفين جدًا لده ⟦2⟧ ⟦0⟧ بخصوص إيه؟' => 'We\'re back to ⟦0⟧ ⟦1⟧
We\'re really sorry about that ⟦2⟧ ⟦0⟧ — what\'s it about?',
    'نرجع لـ⟦0⟧' => 'Back to your ⟦0⟧',
    'نظام البيع "جمله"
البيع مش اقل من ⟦0⟧ دست مشكل
الديجتال مش اقل من ⟦1⟧ دست
و البونيه مش اقل من ⟦2⟧ دست
و الشيلان و الملابس مش اقل من ⟦3⟧. قطع
وتوتال الفاتوره ⟦4⟧
- لابد يكون في منفذ بيع
ممكن حضرتك تتوصلي مع رقم مسئول الجمله : ⟦5⟧' => 'Wholesale pricing
Minimum ⟦0⟧ dozen per item
Digital minimum ⟦1⟧ dozen
Bonnets minimum ⟦2⟧ dozen
Shawls and clothes minimum ⟦3⟧ pieces
Total invoice ⟦4⟧
- Must have a sales outlet
You can reach the wholesale manager at: ⟦5⟧',
    'نكمل' => 'Continue',
    'نوع الشكوى' => 'Complaint type',
    'نوع الطلب' => 'Request type',
    'نوفمبر' => 'November',
    'هنتواصل مع حضرتك باسم ⟦0⟧ على رقم ⟦1⟧ — تمام كده؟' => 'We\'ll contact you at ⟦0⟧ on ⟦1⟧ — is that right?',
    'هو' => 'It',
    'هي' => 'It',
    'و' => 'And',
    'واتس' => 'WhatsApp',
    'واتساب' => 'WhatsApp',
    'وعليكم السلام ورحمة الله' => 'And upon you be peace and God\'s mercy',
    'يا' => 'Hey',
    'يرجى إرسال: الاسم، رقم للتواصل، مع حضرتك فاتورة ؟ ، تاريخ زيارة الفرع' => 'Please send: your name, a contact number, your receipt, and the date you visited the branch',
    'يرجى إرسال: صورة الفاتورة، صورة إيصال الدفع بالفيزا، صورة إيصال الريفوند' => 'Please send: a photo of your receipt, a photo of your card payment proof, and a photo of your refund receipt',
    'يرجي توضيح طريقة الدفع , رقم الاوردر , و وصف المشكله بالتفصيل' => 'Please clarify the payment method, order number, and describe the issue in detail',
    'يرد' => 'reply',
    'يكلمني' => 'talk to me',
    'يناير' => 'January',
    'يوليو' => 'July',
    'يونيو' => 'June',
    'اختاري دي' => 'Pick this one',
    'أرجّع دي' => 'Return this one',
    'أبدّل دي' => 'Exchange this one',
    'أعدّل دي' => 'Change this one',
    'أرجع الباقي كله' => 'Return all the rest',
    'أبدل الباقي كله' => 'Exchange all the rest',
    'أرجع الأوردر كله' => 'Return the whole order',
    'أبدل الأوردر كله' => 'Exchange the whole order',
    'كل القطع اللي فاضلة في طلب واحد' => 'Every remaining piece in one request',
    'أرجع كله' => 'Return everything',
    'أبدل كله' => 'Exchange everything',
    'تحبي أعرضلك المنتجات هنا، ولا تبعتيلي لينك المنتج أو اسمه؟' => 'Shall I show you the products here, or would you rather send me the product link or name?',
    'تمام، هنبدل ⟦0⟧
تحبي تبدلي بإيه؟' => 'Done, we will exchange ⟦0⟧
What would you like instead?',
    'اعرضيلي المنتجات' => 'Show me the products',
    'هبعت لينك أو اسم' => 'I will send a link or name',
    'اختاري المنتج اللي تحبي تبدلي بيه' => 'Pick the product you would like instead',
    'أبدّل بده' => 'Exchange for this',
    'ده المنتج اللي تحبي تبدلي بيه؟' => 'Is this the product you would like instead?',
    'لأ منتج تاني' => 'No, another one',
    'تمام، هنبدل بـ ⟦0⟧' => 'Done, we will exchange it for ⟦0⟧',
    'لقيت أكتر من منتج بالاسم ده، اختاري منهم' => 'I found more than one product with that name, pick one',
    'مش لاقية منتج بالاسم ده، ابعتيلي لينك المنتج من الموقع، أو جربي اسم تاني' => 'I cannot find a product by that name, send me its link from the website, or try another name',
    'الشكوى بخصوص أنهي قطعة؟ ⟦0⟧ ولو على الأوردر كله اضغطي الزرار الأخير' => 'Which piece is the complaint about? ⟦0⟧ If it is about the whole order, tap the last button',
    'الشكوى عن دي' => 'Complaint about this',
    'كل الأوردر' => 'The whole order',
    'صوّري القطعة وابعتيلي صورتها عشان الفريق يشوف العيب، ولو مش معاكي دلوقتي اكتبي ⟦0⟧' => 'Please send me a photo of the piece, so the team can see the defect; if you do not have one right now, type ⟦0⟧',
    'شوفي المنتج' => 'View product',
    'التفاصيل والمقاسات' => 'Details & sizes',
    'الموديلات' => 'Our models',
    'اختاري القطعة دي' => 'Pick this piece',
    'رجّع القطعة دي' => 'Return this piece',
    'بدّل القطعة دي' => 'Exchange this piece',
    'عدّل القطعة دي' => 'Change this piece',
    'الشكوى عن القطعة دي' => 'Complaint about this piece',
    'الشكوى بخصوص أنهي قطعة؟' => 'Which piece is the complaint about?',
    'اختاري القطعة اللي عايزة ترجعيها — اختاري من الصور اللي فوق أو اكتبي رقم القطعة' => 'Pick the piece you want to return — choose from the pictures above or type its number',
    'اختاري القطعة اللي عايزة تبدليها — اختاري من الصور اللي فوق أو اكتبي رقم القطعة' => 'Pick the piece you want to exchange — choose from the pictures above or type its number',
    'اختاري القطعة اللي عايزة ترجعيها أو تبدليها — اختاري من الصور اللي فوق أو اكتبي رقم القطعة' => 'Pick the piece you want to return or exchange — choose from the pictures above or type its number',
    'اختاري القطعة اللي عايزة تعدلي فيها — اختاري من الصور اللي فوق أو اكتبي رقم القطعة' => 'Pick the piece you want to change — choose from the pictures above or type its number',
    'الشكوى بخصوص أنهي قطعة؟ — اختاري من الصور اللي فوق أو اكتبي رقم القطعة' => 'Which piece is the complaint about? — choose from the pictures above or type its number',
];
