<?php

namespace App\Bot\Language;

use App\Models\BotTranslation;
use Illuminate\Console\Command;

/**
 * `php artisan bot:translations --warm` translates every Arabic text the bot can say
 * (TranslationSources) in one go, so the first English customer never waits for a model
 * call mid-conversation. `--export` writes what is in `bot_translations` into
 * database/seeders/data/bot_translations_<locale>.php, the file the migration seeds from
 * — that is how a reviewed set of English travels to the other databases and to the tests.
 */
class TranslationsCommand extends Command
{
    protected $signature = 'bot:translations
        {--locale=en : the language to work on}
        {--warm : translate everything that has no translation yet}
        {--export : write the table into the seed file}
        {--limit=0 : stop after this many new translations (0 = the daily cap)}';

    protected $description = 'Warm and export the bot translations (design 2026-09-21 §2)';

    public function handle(BotTranslator $translator): int
    {
        $locale = (string) $this->option('locale');

        if ($this->option('warm')) {
            $this->warm($translator, $locale);
        }

        if ($this->option('export')) {
            $this->export($locale);
        }

        if (! $this->option('warm') && ! $this->option('export')) {
            $this->components->warn('Nothing to do: pass --warm and/or --export.');
        }

        return self::SUCCESS;
    }

    private function warm(BotTranslator $translator, string $locale): void
    {
        $sources = TranslationSources::all();
        $missing = array_values(array_filter($sources, fn (array $s) => $translator->cached($s['text'], $locale) === null));

        $limit = (int) $this->option('limit');

        if ($limit > 0) {
            $missing = array_slice($missing, 0, $limit);
        }

        $this->components->info(count($sources).' texts, '.count($missing).' without a '.$locale.' translation.');

        // Small batches: one failed call then costs a handful of texts, not all of them.
        foreach (array_chunk($missing, 25) as $chunk) {
            $translator->many(
                array_column($chunk, 'text'),
                $locale,
                'warm',
                array_column($chunk, 'short'),
            );

            $this->output->write('.');
        }

        $this->newLine();
        $usage = $translator->usage();
        $done = count(array_filter($missing, fn (array $s) => $translator->cached($s['text'], $locale) !== null));
        $this->components->info($done.' of '.count($missing).' translated. Used today: '.$usage['used'].'/'.$usage['cap'].'.');

        foreach ($missing as $source) {
            if ($translator->cached($source['text'], $locale) === null) {
                $this->components->warn('still missing ('.$source['context'].'): '.mb_substr($source['text'], 0, 60));
            }
        }
    }

    private function export(string $locale): void
    {
        $rows = BotTranslation::query()->where('locale', $locale)->orderBy('source_text')->get();
        $lines = [];

        foreach ($rows as $row) {
            $lines[] = '    '.var_export((string) $row->source_text, true).' => '.var_export((string) $row->text, true).',';
        }

        $path = self::path($locale);
        $header = <<<PHP
            <?php

            /**
             * Seeded {$locale} translations of the bot's Arabic texts (design 2026-09-21 §2).
             *
             * Keys are the MASKED sources (App\\Bot\\Language\\TranslationMask: numbers, links and
             * emoji replaced by ⟦n⟧), so one entry serves every order number and price.
             *
             * Generated by `php artisan bot:translations --warm --export`, then reviewed by hand.
             * A translation the owner edits in Settings → الترجمات becomes `human` in the database
             * and is never overwritten by this file.
             */
            return [

            PHP;

        file_put_contents($path, $header.implode("\n", $lines)."\n];\n");
        $this->components->info(count($lines).' translations written to '.$path);
    }

    public static function path(string $locale): string
    {
        return database_path('seeders/data/bot_translations_'.$locale.'.php');
    }
}
